[env]
MISE_USE_VERSIONS_HOST = "0"

[tools]
stylua = "latest"

[tasks.format]
description = "Format Lua scripts"
run = "stylua metadata.lua hooks/ lib/"

[tasks.ci]
description = "Run all CI checks"
depends = ["test"]
