[env]
MISE_USE_VERSIONS_HOST = "0"

[tasks.format]
description = "Format Lua scripts"
run = "stylua metadata.lua hooks/ lib/"

[tasks."test"]
description = "Runs all tests"
run = [
    { task = "test:unit" },
    { task = "test:external" },
    { task = "test:e2e" },
]

[tasks."test:unit"]
description = "Runs all unit tests"
dir = "test"
run = "gotestsum -- ./..."

[tasks."test:external"]
description = "Runs all external tests"
dir = "test"
run = "gotestsum -- -tags test_external -run 'External$' ./..."
run_windows = "gotestsum -- -tags test_external -run External$ ./..."

[tasks."test:e2e"]
description = "Runs all E2E tests"
dir = "test"
run = "gotestsum -- -tags test_e2e -run ^TestE2E_ ./..."

[tasks.ci]
description = "Run all CI checks"
run = [
    { task = "test" }
]

[tools]
stylua = "latest"
go = "latest"

[tools.gotestsum]
version = "latest"
platforms.darwin-arm64.assert_pattern = "gotestsum_*_darwin_arm64.tar.gz"
platforms.darwin-x64.assert_pattern = "gotestsum_*_darwin_amd64.tar.gz"
platforms.linux-arm64.assert_pattern = "gotestsum_*_linux_arm64.tar.gz"
platforms.linux-x64.assert_pattern = "gotestsum_*_linux_amd64.tar.gz"
platforms.windows-arm64.assert_pattern = "gotestsum_*_windows_arm64.tar.gz"
platforms.windows-x64.assert_pattern = "gotestsum_*_windows_amd64.tar.gz"

[alias]
gotestsum = "github:gotestyourself/gotestsum"