name: Continues Integration

on:
  push:
    branches: [ main ]

  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

  workflow_dispatch:

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MISE
        uses: jdx/mise-action@v2

      - name: Run tests
        run: mise run ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-legacy:
    name: Test (legacy)
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MISE
        uses: jdx/mise-action@v2
        with:
          version: 2025.10.7

      - name: Run tests
        run: mise run ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
