name: Continues Integration

on:
  push:
    branches: [ main ]

  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

  workflow_dispatch:

jobs:
  test:
    name: Test (mise ${{ matrix.mise-version || 'latest' }} on ${{ matrix.os }})
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        mise-version: [ '', '2025.10.7' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MISE ${{ matrix.mise-version || 'latest' }}
        uses: jdx/mise-action@v2
        with:
          version: ${{ matrix.mise-version }}
          cache: false

      - name: Run tests
        run: mise run ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
